frase = '  Curso em Vídeo Python  '
print(frase)
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[13:])
print(frase[1:15:2])
print(frase[::2])
print("""texto
muito
longo
mesmo""")
print(frase.count('o'))
print(frase.count('O'))
print(frase.upper().count('O'))
print(len(frase))
print(len(frase.strip()))
frase = frase.replace('Python', 'Android')
print('Curso' in frase)
print(frase.find('Curso'))
print(frase.find('Vídeo'))
print(frase.find('vídeo'))
print(frase.lower().find('vídeo'))
dividido = frase.split()
print(frase[2])
print(dividido)
print(dividido[0])
print(dividido[2][4])
